### ISSUE TITLE
static needs to be changed to staticfiles as directory name

### ISSUE THREAD

**Issue by abhigyank** [RobotronicsClubIITMandi/Robotronics-Club-Website#5]
https://github.com/RobotronicsClubIITMandi/Robotronics-Club-Website/blob/d9e5b8bc13d8a1461205df970aec2f0745f8c6e9/robotronics/templates/robotronics/team.html#L30

**Comment by Varunvaruns9** [comment]
Added a fix in 68a8ae4bca. @abhigyank

**Comment by vsvipul** [comment]
i think this can be closed now
